/*
 * File:    Report.cs
 * Purpose: Represents a generated financial report in NeciAI.
 *          Inherits from BaseEntity demonstrating INHERITANCE.
 *          Overrides GetSummary() demonstrating POLYMORPHISM.
 *          Satisfies the rubric requirement for reports with title,
 *          multiple columns, multiple rows, and date-time stamps.
 * Author:  Abraham Macias
 * Date:    June 2026
 */

using System;
using System.ComponentModel.DataAnnotations;

namespace NeciAI.API.Models
{
    /// <summary>
    /// Represents a financial report generated by a user in NeciAI.
    /// Reports contain a title, timestamp, type, and file path to
    /// the generated PDF or Excel document.
    /// </summary>
    public class Report : BaseEntity
    {
        // Report title — displayed at the top of every exported document
        [Required]
        [MaxLength(300)]
        public string Title { get; set; } = string.Empty;

        // Type of report: Forecast, Variance, Anomaly, or CashFlow
        [Required]
        public string ReportType { get; set; } = string.Empty;

        // Format of the exported file: PDF or Excel
        [Required]
        public string Format { get; set; } = "PDF";

        // Date range start for the data included in this report
        public DateTime PeriodStart { get; set; }

        // Date range end for the data included in this report
        public DateTime PeriodEnd { get; set; }

        // Exact timestamp when this report was generated
        public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

        // File path where the generated report document is stored
        public string FilePath { get; set; } = string.Empty;

        // Number of data rows included in this report
        public int RowCount { get; set; }

        // Summary statistics embedded in the report
        public string Summary { get; set; } = string.Empty;

        // Foreign key linking report to the user who generated it
        public string UserId { get; set; } = string.Empty;

        // Navigation property back to the user
        public virtual ApplicationUser User { get; set; } = null!;

        /// <summary>
        /// Overrides GetSummary() to return report-specific information.
        /// Demonstrates POLYMORPHISM alongside FinancialRecord's override.
        /// </summary>
        public override string GetSummary()
        {
            return "[" + ReportType + "] " + Title +
                   " | Generated: " + GeneratedAt.ToString("yyyy-MM-dd HH:mm") +
                   " | Period: " + PeriodStart.ToString("yyyy-MM-dd") +
                   " to " + PeriodEnd.ToString("yyyy-MM-dd") +
                   " | Rows: " + RowCount;
        }
    }
}