// ============================================================
// ReportsController.cs
// Handles PDF and Excel report generation, retrieval,
// download, and deletion for authenticated users.
//
// Author: Abraham Macias
// Route:  /api/Reports
// ============================================================

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NeciAI.API.Interfaces;
using System.Security.Claims;

namespace NeciAI.API.Controllers
{
    /// <summary>
    /// Manages report generation and retrieval.
    /// All endpoints require a valid JWT Bearer token.
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    [Authorize]
    public class ReportsController : ControllerBase
    {
        private readonly IReportService _reportService;

        public ReportsController(IReportService reportService)
        {
            _reportService = reportService;
        }

        /// <summary>
        /// Returns all reports generated by the authenticated user,
        /// ordered by most recently generated first.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var reports = await _reportService.GetReportsByUserAsync(GetUserId());
            return Ok(reports);
        }

        /// <summary>
        /// Returns a single report by ID.
        /// Returns 404 if the report does not exist or belongs to another user.
        /// </summary>
        [HttpGet("{id:int}")]
        public async Task<IActionResult> GetById(int id)
        {
            var report = await _reportService.GetReportByIdAsync(id, GetUserId());
            return report is null
                ? NotFound(new { message = "Report not found." })
                : Ok(report);
        }

        /// <summary>
        /// Generates a PDF financial report for the specified date range.
        /// The report contains a title, timestamp, summary statistics,
        /// and a multi-column, multi-row data table.
        /// </summary>
        [HttpPost("pdf")]
        public async Task<IActionResult> GeneratePdf(
            [FromQuery] string title,
            [FromQuery] DateTime startDate,
            [FromQuery] DateTime endDate)
        {
            if (!ValidateReportRequest(title, startDate, endDate, out var validationError))
                return BadRequest(new { message = validationError });

            var (startUtc, endUtc) = ToUtcRange(startDate, endDate);
            var report = await _reportService.GeneratePdfReportAsync(GetUserId(), title, startUtc, endUtc);

            return Ok(new
            {
                message    = "PDF report generated successfully.",
                reportId   = report.Id,
                title      = report.Title,
                generatedAt = report.GeneratedAt,
                rowCount   = report.RowCount,
                summary    = report.GetSummary(),
            });
        }

        /// <summary>
        /// Generates an Excel financial report for the specified date range.
        /// The report contains formatted columns, row data, and summary totals.
        /// </summary>
        [HttpPost("excel")]
        public async Task<IActionResult> GenerateExcel(
            [FromQuery] string title,
            [FromQuery] DateTime startDate,
            [FromQuery] DateTime endDate)
        {
            if (!ValidateReportRequest(title, startDate, endDate, out var validationError))
                return BadRequest(new { message = validationError });

            var (startUtc, endUtc) = ToUtcRange(startDate, endDate);
            var report = await _reportService.GenerateExcelReportAsync(GetUserId(), title, startUtc, endUtc);

            return Ok(new
            {
                message    = "Excel report generated successfully.",
                reportId   = report.Id,
                title      = report.Title,
                generatedAt = report.GeneratedAt,
                rowCount   = report.RowCount,
                summary    = report.GetSummary(),
            });
        }

        /// <summary>
        /// Streams the report file to the client as a downloadable binary.
        /// Sets the correct Content-Type for PDF or Excel based on the report format.
        /// </summary>
        [HttpGet("{id:int}/download")]
        public async Task<IActionResult> Download(int id)
        {
            var userId = GetUserId();
            var report = await _reportService.GetReportByIdAsync(id, userId);

            if (report is null)
                return NotFound(new { message = "Report not found." });

            var fileBytes = await _reportService.DownloadReportAsync(id, userId);

            if (fileBytes is null)
                return NotFound(new { message = "Report file not found on disk." });

            var (contentType, extension) = report.Format == "PDF"
                ? ("application/pdf", "pdf")
                : ("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx");

            var fileName = $"{report.Title.Replace(" ", "_")}_{report.GeneratedAt:yyyyMMdd}.{extension}";
            return File(fileBytes, contentType, fileName);
        }

        /// <summary>
        /// Soft-deletes a report record and removes its associated file from disk.
        /// Returns 404 if the report does not exist or belongs to another user.
        /// </summary>
        [HttpDelete("{id:int}")]
        public async Task<IActionResult> Delete(int id)
        {
            var success = await _reportService.DeleteReportAsync(id, GetUserId());
            return success
                ? Ok(new { message = "Report deleted successfully." })
                : NotFound(new { message = "Report not found." });
        }

        // ── PRIVATE HELPERS ──────────────────────────────────

        /// <summary>
        /// Extracts the authenticated user's ID from the JWT claims.
        /// Throws if the claim is missing — should never occur for
        /// endpoints decorated with [Authorize].
        /// </summary>
        private string GetUserId() =>
            User.FindFirstValue(ClaimTypes.NameIdentifier)
                ?? throw new UnauthorizedAccessException("User identity claim not found.");

        /// <summary>
        /// Validates that the report title is present and the date range is valid.
        /// Returns false and sets the error message when validation fails.
        /// </summary>
        private static bool ValidateReportRequest(
            string title, DateTime start, DateTime end, out string error)
        {
            if (string.IsNullOrWhiteSpace(title))
            {
                error = "Report title is required.";
                return false;
            }

            if (start > end)
            {
                error = "Start date must be before end date.";
                return false;
            }

            error = string.Empty;
            return true;
        }

        /// <summary>
        /// Converts a DateTime pair to explicit UTC kind.
        /// Required by Npgsql when writing to timestamp with time zone columns.
        /// </summary>
        private static (DateTime start, DateTime end) ToUtcRange(DateTime start, DateTime end) =>
            (DateTime.SpecifyKind(start, DateTimeKind.Utc),
             DateTime.SpecifyKind(end,   DateTimeKind.Utc));
    }
}
