/*
 * File:    ReportsController.cs
 * Purpose: Handles report generation, retrieval, download, and deletion.
 *          Satisfies rubric requirement for reports with title,
 *          multiple columns, multiple rows, and date-time stamps.
 * Author:  Abraham Macias
 * Date:    June 2026
 */

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NeciAI.API.Interfaces;
using System;
using System.Security.Claims;
using System.Threading.Tasks;

namespace NeciAI.API.Controllers
{
    /// <summary>
    /// Manages report generation and retrieval for NeciAI.
    /// All endpoints require authentication.
    /// Routes are prefixed with /api/reports
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    [Authorize]
    public class ReportsController : ControllerBase
    {
        private readonly IReportService _reportService;

        public ReportsController(IReportService reportService)
        {
            _reportService = reportService;
        }

        /// <summary>
        /// GET /api/reports
        /// Returns all reports generated by the authenticated user.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var userId = GetUserId();
            var reports = await _reportService.GetReportsByUserAsync(userId);
            return Ok(reports);
        }

        /// <summary>
        /// GET /api/reports/{id}
        /// Returns a single report by ID.
        /// </summary>
        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(int id)
        {
            var userId = GetUserId();
            var report = await _reportService.GetReportByIdAsync(id, userId);

            if (report == null)
                return NotFound(new { message = "Report not found." });

            return Ok(report);
        }

        /// <summary>
        /// POST /api/reports/pdf
        /// Generates a PDF financial report for the specified date range.
        /// Report includes title, timestamp, and multiple rows/columns.
        /// </summary>
        [HttpPost("pdf")]
        public async Task<IActionResult> GeneratePdf(
            [FromQuery] string title,
            [FromQuery] DateTime startDate,
            [FromQuery] DateTime endDate)
        {
            if (string.IsNullOrWhiteSpace(title))
                return BadRequest(new { message = "Report title is required." });

            if (startDate > endDate)
                return BadRequest(new
                {
                    message = "Start date must be before end date."
                });

            var userId = GetUserId();

            // Convert to UTC to satisfy PostgreSQL timestamp with time zone requirement
            var startUtc = DateTime.SpecifyKind(startDate, DateTimeKind.Utc);
            var endUtc = DateTime.SpecifyKind(endDate, DateTimeKind.Utc);

            var report = await _reportService
                .GeneratePdfReportAsync(userId, title, startUtc, endUtc);

            return Ok(new
            {
                message = "PDF report generated successfully.",
                reportId = report.Id,
                title = report.Title,
                generatedAt = report.GeneratedAt,
                rowCount = report.RowCount,
                summary = report.GetSummary()
            });
        }

        /// <summary>
        /// POST /api/reports/excel
        /// Generates an Excel financial report for the specified date range.
        /// </summary>
        [HttpPost("excel")]
        public async Task<IActionResult> GenerateExcel(
            [FromQuery] string title,
            [FromQuery] DateTime startDate,
            [FromQuery] DateTime endDate)
        {
            if (string.IsNullOrWhiteSpace(title))
                return BadRequest(new { message = "Report title is required." });

            if (startDate > endDate)
                return BadRequest(new
                {
                    message = "Start date must be before end date."
                });

            var userId = GetUserId();

            // Convert to UTC to satisfy PostgreSQL timestamp with time zone requirement
            var startUtc = DateTime.SpecifyKind(startDate, DateTimeKind.Utc);
            var endUtc = DateTime.SpecifyKind(endDate, DateTimeKind.Utc);

            var report = await _reportService
                .GenerateExcelReportAsync(userId, title, startUtc, endUtc);

            return Ok(new
            {
                message = "Excel report generated successfully.",
                reportId = report.Id,
                title = report.Title,
                generatedAt = report.GeneratedAt,
                rowCount = report.RowCount,
                summary = report.GetSummary()
            });
        }

        /// <summary>
        /// GET /api/reports/{id}/download
        /// Downloads the report file as a binary stream.
        /// Returns the correct content type for PDF or Excel.
        /// </summary>
        [HttpGet("{id}/download")]
        public async Task<IActionResult> Download(int id)
        {
            var userId = GetUserId();
            var report = await _reportService.GetReportByIdAsync(id, userId);

            if (report == null)
                return NotFound(new { message = "Report not found." });

            var fileBytes = await _reportService
                .DownloadReportAsync(id, userId);

            if (fileBytes == null)
                return NotFound(new { message = "Report file not found." });

            var contentType = report.Format == "PDF"
                ? "application/pdf"
                : "application/vnd.openxmlformats-officedocument" +
                  ".spreadsheetml.sheet";

            var extension = report.Format == "PDF" ? "pdf" : "xlsx";
            var downloadName =
                $"{report.Title.Replace(" ", "_")}_{report.GeneratedAt:yyyyMMdd}.{extension}";

            return File(fileBytes, contentType, downloadName);
        }

        /// <summary>
        /// DELETE /api/reports/{id}
        /// Deletes a report record and its associated file.
        /// </summary>
        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var userId = GetUserId();
            var success = await _reportService.DeleteReportAsync(id, userId);

            if (!success)
                return NotFound(new { message = "Report not found." });

            return Ok(new { message = "Report deleted successfully." });
        }

        /// <summary>
        /// Extracts the user ID from JWT token claims.
        /// </summary>
        private string GetUserId() =>
            User.FindFirstValue(ClaimTypes.NameIdentifier)
            ?? throw new UnauthorizedAccessException("User not authenticated.");
    }
}