/*
 * File:    IReportService.cs
 * Purpose: Defines the contract for report generation operations.
 *          Satisfies the rubric requirement for reports with multiple
 *          columns, rows, timestamps, and titles.
 * Author:  Abraham Macias
 * Date:    June 2026
 */

using NeciAI.API.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace NeciAI.API.Interfaces
{
    /// <summary>
    /// Interface defining all report generation and retrieval operations.
    /// Implemented by ReportService which generates PDF and Excel reports
    /// with titles, multiple columns, multiple rows, and date-time stamps.
    /// </summary>
    public interface IReportService
    {
        // Generate a PDF report for a user's financial records
        Task<Report> GeneratePdfReportAsync(
            string userId, string title, DateTime startDate, DateTime endDate);

        // Generate an Excel report for a user's financial records
        Task<Report> GenerateExcelReportAsync(
            string userId, string title, DateTime startDate, DateTime endDate);

        // Retrieve all reports generated by a specific user
        Task<IEnumerable<Report>> GetReportsByUserAsync(string userId);

        // Retrieve a single report by its ID
        Task<Report?> GetReportByIdAsync(int id, string userId);

        // Delete a report record and its associated file
        Task<bool> DeleteReportAsync(int id, string userId);

        // Download the generated report file as a byte array
        Task<byte[]?> DownloadReportAsync(int id, string userId);
    }
}